services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: nestjs_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=nest_db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: npm run start:dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    container_name: vue_app
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"  # Vite Dev Server runs on port 5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./proxy/nginx.conf
          target: /etc/nginx/conf.d/default.conf

volumes:
  mysql_data:
